### ISSUE TITLE
Request to change license to Apache-2

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/xMIP#256]
Following up on some talks I had in the past weeks I would like to change the license of xMIP to [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0). 

For this I need the explicit consent of every contributor so far:

Could @aaronspring @markusritschel @keewis @TomNicholas @emaroon indicate below (with a comment) if they are ok with this change? 

Thanks

**Comment by jbusecke** [comment]
Sorry if this was unclear in the original post. It would be swell if you could type out that you are ok with this. Sorry for the initial confusion.

**Comment by emaroon** [comment]
I, Elizabeth Maroon, further consent for you, Julius Busecke, to change the xMIP license to Apache-2.0. 👩‍💻🧐👍

**Comment by aaronspring** [comment]
I, Aaron Spring, further consent for you, Julius Busecke, to change the xMIP license to Apache-2.0. 👩‍💻🧐👍

**Comment by keewis** [comment]
I, Justus Magin, further consent for you, Julius Busecke, to change the xMIP license to Apache-2.0.

**Comment by jbusecke** [comment]
Pinging @markusritschel once again here. If you consent to this change I can go ahead and switch the relevant files.

**Comment by markusritschel** [comment]
Hi @jbusecke,
Sorry for the way too late reply. Yes, absolutely.
I, Markus Ritschel, further consent for you, Julius Busecke, to change the xMIP license to Apache-2.0.

**Comment by jbusecke** [comment]
I just changed the license. Thank you all!
