### ISSUE TITLE
Using `interpolate_grid_label()` to regrid data

### ISSUE THREAD

**Issue by r-ford** [jbusecke/xMIP#262]
I'm trying to put some of the CMIP6 data in the Pangeo Google storage on the same grid in order to take an average across models. I thought that `interpolate_grid_label()` might do this. In [this notebook](https://github.com/r-ford/regrid-cmip6-xmip/blob/main/regrid-cmip6-xmip.ipynb), I am trying to regrid the MPI data from its `gn` grid to the CESM's `gr` grid, but it does not work. Is `interpolate_grid_label()` meant to do this sort of regridding, or could there just be an error in my code?

**Comment by r-ford** [comment]
Thanks @jbusecke! That makes sense. xesmf seems like my best option, though I've been running into some issues getting results so far (one example is in [this other notebook](https://github.com/r-ford/regrid-cmip6-xmip/blob/main/regrid-cmip6-minimal.ipynb), where the regridded data is all `nan`). Do you know of any examples on GitHub or elsewhere of someone regridding this CMIP6 data? Also @brian-rose

**Comment by jbusecke** [comment]
There are some common tricks (I think there is a 'masking' or similar argument that might help you here). But generally this case would be a nice demonstration to include either in the xMIP docs or the [pangeo gallery](https://gallery.pangeo.io).

**Comment by r-ford** [comment]
I was able to regrid the data with xesmf (with the help of [this notebook](https://nordicesmhub.github.io/forces-2021/learning/example-notebooks/xesmf_regridding.html)). I plan on writing up a tutorial to add to the Project Pythia [CMIP6 Cookbook](https://cookbooks.projectpythia.org/cmip6-cookbook/README.html), which is a slightly modified version of the one in the Pangeo gallery. Thanks again for the help!
