### ISSUE TITLE
manually changing dataframe for catalog

### ISSUE THREAD

**Issue by jgiguereCC** [jbusecke/xMIP#284]
Hi! I'm trying to manually change the dataframe for an `esm-datastore` and then assign the moditifed dataframe back to a catalog. I've tried using the functionality shown [here](https://github.com/intake/intake-esm/issues/246) for intake-esm and the `from_df()` method showed [here](https://cmip6-preprocessing.readthedocs.io/en/latest/postprocessing.html), but am getting `AttributeError: can't set attribute` and `AttributeError: from_df` from each of these methods respectively. Is there anything I can do to restrict the dataframe, then a new catalogue from that dataframe? I'm still quite new to using xmip/intake-esm, so apologies if this isn't the intended functionality!

```python
import intake
from xmip.postprocessing import merge_variables
import dask
from xmip.drift_removal import unify_time
from xmip.preprocessing import rename_cmip6
url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
col = intake.open_esm_datastore(url)
scenarios = ["ssp370", "piControl", "historical"]  # set desired scenarios
var_name = 'tos'
time_step = ['Oday']
query = dict(experiment_id = scenarios,
             variable_id=var_name,
             table_id = time_step,
             member_id = 'r1i1p1f1'
            )
cat = col.search(require_all_on="source_id", **query)
correct_order = list(cat.df.columns)
new_df = cat.df.groupby(['source_id','experiment_id']).first().reset_index()[correct_order]
cat.df= new_df
```
Yields the error:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 19
     17 correct_order = list(cat.df.columns)
     18 new_df = cat.df.groupby(['source_id','experiment_id']).first().reset_index()[correct_order]
---> 19 cat.df= new_df

AttributeError: can't set attribute
```

Thanks!

**Comment by jbusecke** [comment]
I think this is a question specific to intake-esm. Would you mind raising the issue over there? Feel free to tag me there, but I think folks over there will be more knowledgable on this.

**Comment by jgiguereCC** [comment]
Thanks, will do!

**Comment by jbusecke** [comment]
I saw that there was a solution posted in https://github.com/intake/intake-esm/issues/579. I will close this if that is ok with you?
